### ISSUE TITLE
scroll wheel false - zoom on scroll

### ISSUE THREAD

**Issue by ocean123** [aptly-io/grav-plugin-googlemaps#1]
Hi,

how can I prevent that the map is zoom on scroll.

```

fullwidth: false
googlemaps:
    map:
        center: '51.743012826013704, 5.46681672334671'
        zoom: 10
        scrollwheel: false
        markers:
            -
                location: '52.843012826013704, 6.16681672334671'
                title: ZoomZoom
                zIndex: 1
                timeout: 1000
                info: 'No zoom zoomzzzzzz'



```

This not working is that correct! And how can I let it stop zooming?

https://developers.google.com/maps/documentation/javascript/reference

**Comment by aptly-io** [comment]
Hello,

Thanks for considering using the googlemaps plugin, hope you enjoy it.

I think it's because the HTML element has focus and gets the mouse 
scroll events.
(that's what I also notice at other pages with maps sometimes).
Just clicking somewhere else in the page and the scroll events don't end 
up in the map.

So maybe add some javascript that puts the focus on another element when 
the page is loaded.

It's a good suggestion and I'll try to add a workaround in a future 
version.
I plan to make a new release somewhere this month (January) if free time 
permits.

Have a nice weekend.

On 2016-01-16 10:23 AM, ocean123 wrote:

> Hi,
> 
> how can I prevent that the map is zoom on scroll
> 
> ```
> 
> fullwidth: false
> googlemaps:
>     map:
>         center: '51743012826013704, 546681672334671'
>         zoom: 10
>         scrollwheel: false
>         markers:
>             -
>                 location: '52843012826013704, 616681672334671'
>                 title: ZoomZoom
>                 zIndex: 1
>                 timeout: 1000
>                 info: 'No zoom zoomzzzzzz'
> 
> 
> 
> ```
> 
> This not working is that correct! And how can I let it stop zooming?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/aptly-io/grav-plugin-googlemaps/issues/1

## 

Kind regards,
francis                   [home page](https://aptly.io)

"Empty cans make the most noise" - Farah Ann Abdul Hadi

**Comment by ocean123** [comment]
Well google maps documents there is already a option for this but your script is not passing it true.
See link for information. https://developers.google.com/maps/documentation/javascript/reference
But I don't have the scales to add this in your script.

**Comment by aptly-io** [comment]
Thanks for mentioning this. I'll add more options in next iteration!

**Comment by aptly-io** [comment]
It should be fixed in the branch grav_v1_checkup.
That's commit 32356179398a589ebefc2df604505effb56fc900.

**Comment by ocean123** [comment]
Googlemaps plugin version # v0.2.2 is still zooming when scrolling over...?

**Comment by aptly-io** [comment]
Hi Ocean123,

As mentioned before, please use the branch grav_v1_checkup:
https://github.com/aptly-io/grav-plugin-googlemaps/tree/grav_v1_checkup
You might want to read the README.md

This branch is not released yet; you have to get this manually.
Something like this for a Mac or Unix command line:

``` bash
cd your-path-for-your-grav
bin/grav clearcache                             # cleanup grav's cache
cd user/plugins                                 # go into your grav's plugin directory
rm -rf googlemaps                               # remove your existing googlemaps
git clone https://github.com/aptly-io/grav-plugin-googlemaps.git   # get the googlemaps repository locally into the plugin directory
mv grav-plugin-googlemaps googlemaps            # rename the local repository directory
cd googlemaps                                   # gets into the googlemaps local repository
git checkout grav_v1_checkup                    # this switches to the branch with fixes
```

Now start grav again and check your site ...

```
```
